apiVersion: v1
kind: ResourceQuota
metadata:
  name: backend-quota
  namespace: backend-namespace
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
    pods: "10"
    services: "5"

