apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.backend.namespace }}
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}


