apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJoYWdlcnJhbWFkYW4iLCJwYXNzd29yZCI6Im07N1RHdmRwR2c7YiwqbiIsImVtYWlsIjoiaGFnZXJyYW1hZGFuNjMyMDAzQGdtYWlsLmNvbSIsImF1dGgiOiJhR0ZuWlhKeVlXMWhaR0Z1T20wN04xUkhkbVJ3UjJjN1lpd3FiZz09In19fQ==
kind: Secret
metadata:
  name: dockerhub-secret
type: kubernetes.io/dockerconfigjson
